version: 2
updates:
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
    target-branch: "develop"
    groups:
      patch-and-minor:
        update-types:
          - "minor"
          - "patch"
    labels:
      - "dependencies"
