version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.11"
  apt_packages:
    - libgirepository1.0-dev

sphinx:
  configuration: docs/source/conf.py

python:
  install:
    - method: pip
      path: .
