name: ruff
on: push

jobs:
  ruff:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          python-version: "3.13"

      - name: Install system dependencies
        run: sudo apt-get install -y python3-gi python3-gi-cairo gir1.2-aravis-0.8

      - name: Install packages
        run: uv venv --system-site-packages .venv && uv sync --all-extras --dev

      - name: Run ruff
        run: uv run --no-sync ruff check pyobs_aravis/
